# This is a basic workflow to help you get started with Actions

name: CONTAINER

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:14.15.4-alpine3.10
    steps:
      - name: Version
        run: node -v
      - name: steps-with-docker
        uses: docker://node:14.15.4-buster
        with:
          entrypoint: 'bin/echo' 
          args: 'hello worlds' 

      - name: steps-with-docker-2
        uses: docker://node:14.15.4-buster
        with:
          entrypoint: /usr/local/bin/node 
          args: -v 

            
