name: SHOUDL_SHOW_CONTEXT_VARIABLE

on: 
  workflow_dispatch:
  
  repository_dispatch:
    types: [variable]

jobs:
  one:
    runs-on: ubuntu-latest
     # wszytsko co jest w if - jets traktowane jako expression ${{}}
    # if: 
    #   github.event_name ==  'push'
    timeout-minutes: 5  
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        if: failure()
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "POWINNO BYC $JOB_CONTEXT"
        continue-on-error: true
      - name: Dump steps context
        if: success()
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "NIE POWINNO $STEPS_CONTEXT"
      - name: Dump runner context
        if: always()
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "POWINNO $RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"


#         contains(github.event.issue.labels.*.name, 'bug')
#         startsWith( searchString, searchValue )
#         endsWith( searchString, searchValue )
#         format( string, replaceValue0, replaceValue1, ..., replaceValueN)
#         Returns 'Hello Mona the Octocat'

# format('Hello {0} {1} {2}', 'Mona', 'the', 'Octocat')