name: SHOULD_USE_ENV_VAR_AND_ADD_TO_GIT_FILE
on:

  workflow_dispatch:
  
  repository_dispatch:
    types: [git]

env:
  WF_ENV: ${{secrets.WF_ENV}} TEST 1

jobs:
  add_file_to_git:
    runs-on: ubuntu-latest
    steps:
      - name: Push
        run: |
          pwd
          ls -a
          git init
          echo " GITHUB_ACTOR  $GITHUB_ACTOR "
          echo " GITHUB_REPOSITORY $GITHUB_REPOSITORY"
          echo  "$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"

          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"

          git config --global user.email "my-bot@bot.com"
          git config --global user.name "my-bot@bot.com"
          git fetch 
          git checkout master
          git branch --set-upstream-to=origin/master
          git pull
          ls -a
          echo $RANDOM >> random.txt
          git add -A
          git commit -m "random file"
          git push
  # decrypt:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: action/checkout@v1
  #     - name: Decrypt
  #       run: gpg --quiet --batch --yes --decrypt --passpharse="$PASSPHARSE"  --output $HOME/secret.json
  #       env:
  #         PASSPHARSE: ${{secrets.PASSPHARSE}}
  log_env_variables:
    needs: [add_file_to_git]

    runs-on: ubuntu-latest
    timeout-minutes: 5  
    env:
      JOB_ENV: Avalible to all stpes TEST 2
    steps: 
      - name: local Env
        env: 
          STEP_ENV: local
        run: |
          echo "WF_ENV: OK ${WF_ENV} "
          echo "JOB_ENV: OK ${JOB_ENV} "     
          echo "STEP_ENV: OK ${STEP_ENV} " 
      - name: Log Env Var in diffrent steps
        run: |
          echo "WF_ENV: OK2 ${WF_ENV} "
          echo "JOB_ENV: OK2 ${JOB_ENV} "
          echo "STEP_ENV: SHOULD FAIL ${STEP_ENV} " 

  create_issue:
    needs: [log_env_variables]
    runs-on: ubuntu-latest
    steps:
      - name: GITHUB Env
        run: |
          echo "${HOME}"
          echo "${HOME}"
          echo "${GITHUB_ACTION}"
          echo "${GITHUB_ACTIONS}"
  
      - name: Create issue using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
          "title": "TITLE:  Automated issue for commit: ${{ github.sha }}",
          "body": "BODY: This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
          }'