# This is a basic workflow to help you get started with Actions

name: SHULD_BUILD_USE_MATRIX

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
 
  repository_dispatch:
    types: [matrix]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  node-VERSION:
    timeout-minutes: 5  

    strategy:
      fail-fast: true # nawet jak jedno padnie 6 , 8 , 10 - bo we wszystkich srodowiskach bedzie to zrobione - jak tru - padnie - jak fail - reszta tez sproboje run
      matrix: 
        # os: [ macos-latest, ubuntu-latest]   # to jest płacone z runs-on
        node_version: [6,8,10]
        exclude: 
          - node_version: 6
          #os: ubuntu-letest

    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: log node version
        run: node -v
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version}}
      - run: node -v